plugins = [
    "!error",
]
packages = [
    "/static/wheels/annotated_types-0.7.0-py3-none-any.whl",
    "/static/wheels/anyio-4.11.0-py3-none-any.whl",
    "/static/wheels/certifi-2025.8.3-py3-none-any.whl",
    "/static/wheels/cffi-2.0.0-cp313-cp313-win_amd64.whl",
    "/static/wheels/charset_normalizer-3.4.3-cp313-cp313-win_amd64.whl",
    "/static/wheels/clr_loader-0.2.7.post0-py3-none-any.whl",
    "/static/wheels/cryptography-46.0.1-cp311-abi3-win_amd64.whl",
    "/static/wheels/deprecation-2.1.0-py2.py3-none-any.whl",
    "/static/wheels/h11-0.16.0-py3-none-any.whl",
    "/static/wheels/h2-4.3.0-py3-none-any.whl",
    "/static/wheels/hpack-4.1.0-py3-none-any.whl",
    "/static/wheels/httpcore-1.0.9-py3-none-any.whl",
    "/static/wheels/httpx-0.28.1-py3-none-any.whl",
    "/static/wheels/hyperframe-6.1.0-py3-none-any.whl",
    "/static/wheels/idna-3.10-py3-none-any.whl",
    "/static/wheels/jbkgestione-0.0.1-py3-none-any.whl",
    "/static/wheels/packaging-25.0-py3-none-any.whl",
    "/static/wheels/pillow-11.3.0-cp313-cp313-win_amd64.whl",
    "/static/wheels/postgrest-2.20.0-py3-none-any.whl",
    "/static/wheels/pycparser-2.23-py3-none-any.whl",
    "/static/wheels/pydantic-2.11.9-py3-none-any.whl",
    "/static/wheels/pydantic_core-2.33.2-cp313-cp313-win_amd64.whl",
    "/static/wheels/PyJWT-2.10.1-py3-none-any.whl",
    "/static/wheels/python_dotenv-1.1.1-py3-none-any.whl",
    "/static/wheels/pythonnet-3.0.5-py3-none-any.whl",
    "/static/wheels/realtime-2.20.0-py3-none-any.whl",
    "/static/wheels/requests-2.32.5-py3-none-any.whl",
    "/static/wheels/sniffio-1.3.1-py3-none-any.whl",
    "/static/wheels/storage3-2.20.0-py3-none-any.whl",
    "/static/wheels/StrEnum-0.4.15-py3-none-any.whl",
    "/static/wheels/supabase-2.20.0-py3-none-any.whl",
    "/static/wheels/supabase_auth-2.20.0-py3-none-any.whl",
    "/static/wheels/supabase_functions-2.20.0-py3-none-any.whl",
    "/static/wheels/toga-0.5.2-py3-none-any.whl",
    "/static/wheels/toga_core-0.5.2-py3-none-any.whl",
    "/static/wheels/toga_web-0.5.2-py3-none-any.whl",
    "/static/wheels/toga_winforms-0.5.2-py3-none-any.whl",
    "/static/wheels/travertino-0.5.2-py3-none-any.whl",
    "/static/wheels/typing_extensions-4.15.0-py3-none-any.whl",
    "/static/wheels/typing_inspection-0.4.1-py3-none-any.whl",
    "/static/wheels/urllib3-2.5.0-py3-none-any.whl",
    "/static/wheels/websockets-15.0.1-cp313-cp313-win_amd64.whl",
]
